source 'https://github.com/CocoaPods/Specs.git'

target 'JsonDB-Tests-iOS' do
  platform :ios, '6.0'
  pod 'JsonDB', :path => '../'
  pod 'Specta', '~> 1.0'
  pod 'Expecta', '~> 1.0'
end

target 'JsonDB-Tests-OSX' do
  platform :osx, '10.8'
  pod 'JsonDB', :path => '../'
  pod 'Specta', '~> 1.0'
  pod 'Expecta', '~> 1.0'
end

target 'JsonDB-Demo-iOS' do
  platform :ios, '7.0'
  pod 'JsonDB', :path => '../'
  pod 'JSONSyntaxHighlight', '~> 1.0.0'
  pod 'TRZSlideLicenseViewController', '~> 0.9'
end
