source 'https://github.com/CocoaPods/Specs.git'

target 'JsonDB-Tests-iOS' do
  platform :ios, '5.0'
  pod 'JsonDB', :path => '../'
  pod 'Specta', '~> 0.0'
  pod 'Expecta', '~> 0.0'
end

target 'JsonDB-Tests-OSX' do
  platform :osx, '10.7'
  pod 'JsonDB', :path => '../'
  pod 'Specta', '~> 0.0'
  pod 'Expecta', '~> 0.0'
end

target 'JsonDB-Demo-iOS' do
  platform :ios, '5.0'
  pod 'JsonDB', :path => '../'
  pod 'JSONSyntaxHighlight', '~> 1.0.0'
  # pod 'QuickDialog', '~> 1.0'
end
